### ISSUE TITLE
Conversing with Koko

### ISSUE THREAD

**Issue by tbrannam** [m0ngr31/koko#1]
It appears that I can only interact with the Koko skill on a device by first using command 'alexa open koko' and then issuing commands.  Conversational attempts of 'alexa ask koko to play music by the beatles' usually causes Amazon Music Unlimited to be invoked.

It's not clear to me yet if this is user error - or if this is a limit of how 'developer skills' are invoked.

**Comment by rprior04938** [comment]
It's not a user error.  This custom skill does require you to either use a phrase like "Alexa, tell koko to …."
You are correct that you can "open" the custom skill and then not need to say "Alexa, tell koko to..." each time.  The custom skill does "expire" after a time and it becomes necessary to open it again.  There are, by the way, to my knowledge virtually no koko users actually using it.  I think that the majority of Kodi users use it as a video media server, and koko is really designed for streaming audio.  I've spent a number of months fiddling with koko without "durable" success, at least in part because koko needs to sit behind an https interface, and Kodi doesn't provide one.

By the way, I've had somewhat more success with the phrase "Alexa, TELL koko to …" rather than "Alexa, ASK koko to …"  However I still have the same problem that you do in that the error correction facilities within the koko custom skill are insufficiently developed and failure of parsing a request to koko dumps you to the regular Alexa request management.  Those facilities might be able to be further developed with modest technical skills in the use of the Amazon Alexa custom development tools.

**Comment by tbrannam** [comment]
Great feedback.  I'll log some more time on the code and read up on Alexa skill development kit.  It was pretty cool to get some music flowing.

**Comment by m0ngr31** [comment]
> However I still have the same problem that you do in that the error correction facilities within the koko custom skill are insufficiently developed and failure of parsing a request to koko dumps you to the regular Alexa request management.

That's not exactly the case. The problem is Amazon isn't parsing the data correctly since they don't have enough of a model to make it work properly so it's not even invoking the skill to begin with. It's something we just have to keep going into the Alexa app and review failed invocations to mark them as "No this didn't do what I expected" and hope that it'll start working how it should if more people use it.

**Comment by rprior04938** [comment]
Hi, Joe.  Thanks for the reply, and for clarifying the problem with failed invocations.  I’m happy to see that you’re still paying some attention to the Kodi/Kanzi skills.

 

I actually am still having problems with the https proxy and have moved away from Koko the last 6-8 weeks.  I ran into a warning on the AWS website about NgInx and (I think) Kodi’s web browsers that they may not work well with Lambda apps.  I’ve started to play with Apache on the Raspberry Pi, trying to set it up as a reverse proxy along with Kodi’s own web app.  Maybe I’ll get back to it.  The paper I was working with some old colleagues on has been accepted for publication, and I have more time now.

 

Your suggestion about reporting invocation failures is a good idea.  I also thought that maybe enriching the Alexa skill itself with more utterances might be helpful.  Finally, some troubleshooting tips would be helpful – how to look at the Kodi, the Alexa app, the S3 database, the Lambda app, and finally the cache database for Koko, and understanding how they interact.

 

Best to you.

 

Rod

**Comment by tbrannam** [comment]
Was there a reason why the Alexa Music Skill wasn't used instead of a custom skill?  Perhaps it was just a goal to not have anything custom running on Kodi?  I could see advantages of uploading a music catalog to update a voice model would improve recognition

**Comment by rprior04938** [comment]
If I understand your question, you’re suggesting uploading the music you already own (via CD’s or digital files) to Amazon Music and then using Alexa to listen to that content.  Amazon’s model is one of paid streaming.  They shut off the ability to upload your own music to their cloud.  See this explanation:  http://www.aftvnews.com/amazon-music-no-longer-allows-customers-to-upload-their-own-songs/.  This seems to be true even if you pay for an Amazon Music subscription.

**Comment by tbrannam** [comment]
Oh no not that -- I've been working to understand the implications of https://developer.amazon.com/docs/custom-skills/built-in-intent-library.html#music - which seems to be dependent on a 'Catalog'  I've pretty familiar with Custom Intents - but haven't interacted much with the built-in-intent-library.  I'd suspect that the Catalog would just be an export of the Kodi JsonRPFC API metadata.  But before exploring this I wasn't to see if there was previous thoughts on this in the past or if this was incompatible somehow with the rest of the goals of Koko or Kanzi
